#!/bin/bash

LOG_FILE="/var/log/backup.log"
exec > "$LOG_FILE" 2>&1

TOKEN="Your_token_bot"
CHAT_ID="Your_chat_ID"

DATE=$(date +%d-%m-%Y)
DB="/etc/x-ui/x-ui.db"
if [ -f "$DB" ]; then
    NAME="Backup server $DATE.db"
    cp "$DB" "/tmp/$NAME"
    curl -s -F document=@"/tmp/$NAME" -F "chat_id=$CHAT_ID" -F "caption=Server's backup has been upload✅" "https://api.telegram.org/bot$TOKEN/sendDocument"
    rm "/tmp/$NAME"
else
    echo "DB not found at /etc/x-ui/x-ui.db"
fi
#APT update and remove log's "residual files" apt 
rm -rf /var/log/journal
apt autoremove --purge -y
apt clean
apt update && apt upgrade -y
printf "\n\n0\n" | x-ui update
if reboot; then
echo "reboot..."
else
echo "not reboot"
f
